env:
  browser: true
  es6: true
  cypress/globals: true
extends:
  - airbnb-base
  - plugin:cypress/recommended
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules: {}
